package app

import llmrequest "github.com/bogachenko/tokenio-gateway/internal/application/llmrequest"

type LLMRequestAuthenticator = llmrequest.LLMRequestAuthenticator
type LLMRequestBillingAdmitter = llmrequest.LLMRequestBillingAdmitter
type LLMRequestAutoCharger = llmrequest.LLMRequestAutoCharger
type LLMRequestFinalizer = llmrequest.LLMRequestFinalizer
type LLMRequestForwardingExecutor = llmrequest.LLMRequestForwardingExecutor
type LLMRequestRoutePreflighter = llmrequest.LLMRequestRoutePreflighter
type LLMRequestRouteSelector = llmrequest.LLMRequestRouteSelector
type LLMRequestUsageResolver = llmrequest.LLMRequestUsageResolver

var NewLLMRequestAuthenticator = llmrequest.NewLLMRequestAuthenticator
var NewLLMRequestBillingAdmitter = llmrequest.NewLLMRequestBillingAdmitter
var NewLLMRequestAutoCharger = llmrequest.NewLLMRequestAutoCharger
var NewLLMRequestFinalizer = llmrequest.NewLLMRequestFinalizer
var NewLLMRequestForwardingExecutor = llmrequest.NewLLMRequestForwardingExecutor
var NewLLMRequestRoutePreflighter = llmrequest.NewLLMRequestRoutePreflighter
var NewLLMRequestRouteSelector = llmrequest.NewLLMRequestRouteSelector
var NewLLMRequestUsageResolver = llmrequest.NewLLMRequestUsageResolver
